### ISSUE TITLE
Navigationsspalte fixed

### ISSUE THREAD

**Issue by dtpop** [clicksports/be_theme#14]
Schön wäre, wenn die Navigationsspalte fix positioniert werden könnte. Teilweise sind Seiten recht lang und bei einer fixierten Navigationsspalte würde man nicht mehr Hochscrollen.

**Comment by clicksports** [comment]
Das ist nicht immer möglich, da die Navigationsspalte manchmal höher sein kann als die Desktophöhe

**Comment by clicksports** [comment]
Das ist nicht immer möglich, da die Navigationsspalte manchmal höher sein kann als die Desktophöhe
